sudo: required
services:
  - docker

before_install:
  - docker build -t hardieahmed/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true hardieahmed/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-134777723064"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  